GET http://localhost:3001/email
content-type: application/json

{
    "emailAddress": "sample@gmail.com"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "userName": "stevensa12",
    "password": "482412Ss"
}

###
GET http://192.168.1.2:3001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Nzk0ZjE5NmY2NTM5YzIxNWJhOWY0NSIsInVzZXJOYW1lIjoic3RldmVuc2ExMiIsImVtYWlsQWRkcmVzcyI6InN0ZXZlbi5hcHBzLnBhaWRAZ21haWwuY29tIiwiaWF0IjoxNzAyNDU1MTUwLCJleHAiOjE3MDI1NDE1NTB9.oZe2-9uL7CnFGVnsc1IXb91EzWdA6ZnbRvAzjuCL7Ew

###
GET http://localhost:3001/email?emailAddress=steven.soewignyo@gmail.com

###
GET http://localhost:3001/presigned-url?filename=123.txt

###
GET https://stevensa1.github.io/api-wilayah-indonesia/api/provinces.json

###
GET https://stevensa1.github.io/api-wilayah-indonesia/api/regencies/11.json