import mongoose from 'mongoose';

const PurchasedTicketSchema = mongoose.Schema({
    ticketDestinationId: {
        type: String,
        required: true,
    },
    ticketId: {
        type: String,
        required: true,
    },
    destinationName: {
        type: String,
        required: true,
        default: 'Undefined',
    },
    ticketKind: {
        type: String,
        required: true,
    },
    ticketPrice: {
        type: Number,
        required: true,
    },
    ticketDate: {
        type: Date,
        required: true,
        default: Date.now,
    },
    ticketNameHolder: {
        type: String,
        required: true,
    },
    ticketAgeHolder: {
        type: Number,
        required: true,
        default: 0,
    },
    ticketUserId: {
        type: String,
        required: true,
    },
    ticketPartnerId: {
        type: String,
        required: true,
    },
    // Generated by the server
    ticketBarcode: {
        type: String,
        required: true,
    },
    purchasedTime: {
        type: Date,
        required: true,
        default: Date.now,
    },
});

export default mongoose.model(
    'PurchasedTicket',
    PurchasedTicketSchema,
    'purchased-tickets'
);
